# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75ce3d47c19d6e35d5203ae3db95d3fe9bb0d18511239f82378f191a777c82788ba31588aea8b6a5c14830173c90c650626a2d0521aacf041d559e7ab798ad67

test:
  secret_key_base: 8f401c28dd51ccccd27bbd5f9971f53db99906367a32ee3c7db93d2ad10d64f807e40d8ce33655bc5b0e4d118be76430715289cdcbd6254376ddff5d3d6864f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
